version: '3'

services:

  database:

    image: "postgres"  # use the latest postgres version

    ports:

      - "5432:5432"

    env_file:

      - postgresql.env # postgres configuration data

    volumes:

      - dbdata:/var/lib/postgresql/data

volumes:

  dbdata: